name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run Unit Tests
      run: pytest tests/unit_tests.py

    - name: Static Code Analysis
      run: pylint myapp

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
    - uses: actions/checkout@v2

    - name: Deploy to Testing Environment
      run: |
        # Add deployment scripts here. Example:
        scp -r * user@your-testing-server:/path/to/app
        ssh user@your-testing-server 'cd /path/to/app && ./deploy.sh'
      env:
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
